/home/users/agladckov/ansenv/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
51.250.18.110 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
2022-12-19 01:54:22,133 p=18179 u=agladckov n=ansible | 51.250.18.110 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "ping": "pong"
}
 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:22,747 p=18203 u=agladckov n=ansible |  ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:22,781 p=18203 u=agladckov n=ansible |  ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


/home/users/agladckov/ansenv/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ok: [51.250.18.110]
2022-12-19 01:54:23,623 p=18203 u=agladckov n=ansible | ok: [51.250.18.110]
 ______________________________________
< TASK [update&install basic programs] >
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:23,659 p=18203 u=agladckov n=ansible |  ______________________________________
< TASK [update&install basic programs] >
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [51.250.18.110]
2022-12-19 01:54:24,934 p=18203 u=agladckov n=ansible | ok: [51.250.18.110]
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:24,974 p=18203 u=agladckov n=ansible |  ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


51.250.18.110              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2022-12-19 01:54:24,975 p=18203 u=agladckov n=ansible | 51.250.18.110              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

/home/users/agladckov/ansenv/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ERROR! A malformed block was encountered while loading a block. The ds ([AnsibleMapping([('name', 'get date and time'), ('vars', AnsibleMapping([('msg', 'Date: {{ ansible_date_time.date }}\nTimezone: {{ ansible_date_time.tz }}\n')])), ('copy', AnsibleMapping([('dest', './date_time'), ('content', '{{ msg }}')]))]), AnsibleMapping([('name', 'network info'), ('vars', AnsibleMapping([('msg', 'All Interface List: {{ ansible_interfaces }}\nAll IP: {{ ansible_all_ipv4_addresses }}\nGateway: {{ ansible_default_ipv4.gateway }}\nEth0 MAC: {{ ansible_eth0.macaddress }}\n')])), ('copy', AnsibleMapping([('dest', './network'), ('content', '{{ msg }}')]))]), AnsibleMapping([('name', 'OS and Kernel info'), ('vars', AnsibleMapping([('msg', 'Distribution: {{ ansible_distribution }}\nRelease: {{ ansible_distribution_release }}\nDistribution Version: {{ ansible_distribution_version }}\nKernel: {{ ansible_kernel }}\nArchitecture: {{ ansible_architecture }}\n')])), ('copy', AnsibleMapping([('dest', './os_kernel'), ('content', '{{ msg }}')]))]), AnsibleMapping([('name', 'get hardware info'), ('vars', AnsibleMapping([('msg', 'CPU: {{ ansible_processor }}\nCPU Core: {{ ansible_processor_cores }}\nRAM: {{ ansible_memtotal_mb }}\nSWAP: {{ ansible_memory_mb.swap.total }}\n')])), ('copy', AnsibleMapping([('dest', './hardware'), ('content', '{{ msg }}')]))]), 'name', AnsibleMapping([('name', 'unite files in a node'), ('ansible.builtin.shell', 'cat hostname date_time network os_kernel hardware > send_info.txt')]), AnsibleMapping([('name', 'collect files from nodes'), ('ansible.builtin.fetch', AnsibleMapping([('src', 'send_info.txt'), ('dest', 'info/info_{{ inventory_hostname }}.txt'), ('flat', True)]))])]) should be a dict but was a <class 'list'>
2022-12-19 01:54:25,549 p=18237 u=agladckov n=ansible | ERROR! A malformed block was encountered while loading a block. The ds ([AnsibleMapping([('name', 'get date and time'), ('vars', AnsibleMapping([('msg', 'Date: {{ ansible_date_time.date }}\nTimezone: {{ ansible_date_time.tz }}\n')])), ('copy', AnsibleMapping([('dest', './date_time'), ('content', '{{ msg }}')]))]), AnsibleMapping([('name', 'network info'), ('vars', AnsibleMapping([('msg', 'All Interface List: {{ ansible_interfaces }}\nAll IP: {{ ansible_all_ipv4_addresses }}\nGateway: {{ ansible_default_ipv4.gateway }}\nEth0 MAC: {{ ansible_eth0.macaddress }}\n')])), ('copy', AnsibleMapping([('dest', './network'), ('content', '{{ msg }}')]))]), AnsibleMapping([('name', 'OS and Kernel info'), ('vars', AnsibleMapping([('msg', 'Distribution: {{ ansible_distribution }}\nRelease: {{ ansible_distribution_release }}\nDistribution Version: {{ ansible_distribution_version }}\nKernel: {{ ansible_kernel }}\nArchitecture: {{ ansible_architecture }}\n')])), ('copy', AnsibleMapping([('dest', './os_kernel'), ('content', '{{ msg }}')]))]), AnsibleMapping([('name', 'get hardware info'), ('vars', AnsibleMapping([('msg', 'CPU: {{ ansible_processor }}\nCPU Core: {{ ansible_processor_cores }}\nRAM: {{ ansible_memtotal_mb }}\nSWAP: {{ ansible_memory_mb.swap.total }}\n')])), ('copy', AnsibleMapping([('dest', './hardware'), ('content', '{{ msg }}')]))]), 'name', AnsibleMapping([('name', 'unite files in a node'), ('ansible.builtin.shell', 'cat hostname date_time network os_kernel hardware > send_info.txt')]), AnsibleMapping([('name', 'collect files from nodes'), ('ansible.builtin.fetch', AnsibleMapping([('src', 'send_info.txt'), ('dest', 'info/info_{{ inventory_hostname }}.txt'), ('flat', True)]))])]) should be a dict but was a <class 'list'>
 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:28,175 p=18246 u=agladckov n=ansible |  ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:28,210 p=18246 u=agladckov n=ansible |  ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


/home/users/agladckov/ansenv/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ok: [51.250.18.110]
2022-12-19 01:54:29,044 p=18246 u=agladckov n=ansible | ok: [51.250.18.110]
 _______________________________________
< TASK [Sending an email using Ansible] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:29,084 p=18246 u=agladckov n=ansible |  _______________________________________
< TASK [Sending an email using Ansible] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [51.250.18.110]
2022-12-19 01:54:30,239 p=18246 u=agladckov n=ansible | ok: [51.250.18.110]
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

2022-12-19 01:54:30,291 p=18246 u=agladckov n=ansible |  ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


51.250.18.110              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2022-12-19 01:54:30,292 p=18246 u=agladckov n=ansible | 51.250.18.110              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

